<a href="https://colab.research.google.com/github/LatiefDataVisionary/data-science-application-college-task/blob/main/numpy_pandas_implementaion_w4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **1. Mengimport Library**

In [2]:
import numpy as np
import pandas as pd

print(np.__version__)
print(pd.__version__)

1.26.4
2.2.2


## **2. Load Dataset**

In [3]:
df = pd.read_csv('https://raw.githubusercontent.com/LatiefDataVisionary/data-science-application-college-task/refs/heads/main/datasets/diamonds.csv')

## **3. Melihat Informasi Dasar Dataset (Pandas)**

In [4]:
df.head() # menampilkan 5 baris pertama

Unnamed: 0  carat      cut color clarity  depth  table  price     x     y  \
0           1   0.23    Ideal     E     SI2   61.5   55.0    326  3.95  3.98   
1           2   0.21  Premium     E     SI1   59.8   61.0    326  3.89  3.84   
2           3   0.23     Good     E     VS1   56.9   65.0    327  4.05  4.07   
3           4   0.29  Premium     I     VS2   62.4   58.0    334  4.20  4.23   
4           5   0.31     Good     J     SI2   63.3   58.0    335  4.34  4.35   

      z  
0  2.43  
1  2.31  
2  2.31  
3  2.63  
4  2.75

In [6]:
df.describe()  # Menampilkan statistik deskriptif

Unnamed: 0         carat         depth         table         price  \
count  53940.000000  53940.000000  53940.000000  53940.000000  53940.000000   
mean   26970.500000      0.797940     61.749405     57.457184   3932.799722   
std    15571.281097      0.474011      1.432621      2.234491   3989.439738   
min        1.000000      0.200000     43.000000     43.000000    326.000000   
25%    13485.750000      0.400000     61.000000     56.000000    950.000000   
50%    26970.500000      0.700000     61.800000     57.000000   2401.000000   
75%    40455.250000      1.040000     62.500000     59.000000   5324.250000   
max    53940.000000      5.010000     79.000000     95.000000  18823.000000   

                  x             y             z  
count  53940.000000  53940.000000  53940.000000  
mean       5.731157      5.734526      3.538734  
std        1.121761      1.142135      0.705699  
min        0.000000      0.000000      0.000000  
25%        4.710000      4.720000      2.910000  
50%        5.700000      5.710000      3.530000  
75%        6.540000      6.540000      4.040000  
max       10.740000     58.900000     31.800000

In [5]:
df.info()   # Menampilkan informasi dataset

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 53940 entries, 0 to 53939
Data columns (total 11 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   Unnamed: 0  53940 non-null  int64  
 1   carat       53940 non-null  float64
 2   cut         53940 non-null  object 
 3   color       53940 non-null  object 
 4   clarity     53940 non-null  object 
 5   depth       53940 non-null  float64
 6   table       53940 non-null  float64
 7   price       53940 non-null  int64  
 8   x           53940 non-null  float64
 9   y           53940 non-null  float64
 10  z           53940 non-null  float64
dtypes: float64(6), int64(2), object(3)
memory usage: 4.5+ MB


In [35]:
# Hapus kolom 'Unnamed: 0'
df = df.drop('Unnamed: 0', axis=1)

## **4. Menggunakan NumPy untuk Analisis Numerik**

---




In [7]:
# Mengambil kolom 'price' sebagai array NumPy
prices = df['price'].values

# Menghitung rata-rata harga
mean_price = np.mean(prices)
print(f'Rata-rata harga: ${float(mean_price):.2f}')

Rata-rata harga: $3932.80


In [8]:
# Menghitung median harga
median_price = np.median(prices)
print(f'Median harga: ${float(median_price):.2f}')

Median harga: $2401.00


In [9]:
# Menghitung standar deviasi harga
std_price = np.std(prices)
print(f"Standar deviasi harga: {float(std_price):.2f}")

Standar deviasi harga: 3989.40


In [10]:
# Menghitung nilai maksimum dan minimum harga
max_price = np.max(prices)
min_price = np.min(prices)

print(f'Harga maksimum: ${max_price:.2f}')
print(f'Harga minimum: ${min_price:.2f}')

Harga maksimum: $18823.00
Harga minimum: $326.00


In [11]:
# Menghitung korelasi antara 'carat' dan 'price'
carat = df['carat'].values
correlation_carat_price = np.corrcoef(carat, prices)[0, 1]
print(f'Korelasi antara carat dan price: {correlation_carat_price:.2f}')

Korelasi antara carat dan price: 0.92


In [12]:
# Menghitung nilai maksimum dan minimum carat
max_carat = np.max(carat)
min_carat = np.min(carat)

print(f'Carat maksimum: {max_carat:.2f}')
print(f'Carat minimum: {min_carat:.2f}')

Carat maksimum: 5.01
Carat minimum: 0.20


## **5. Filtering Data**

### **Filtering Data dengan Numpy**

In [13]:
# Filter Harga diatas $10.000
high_prices = prices[prices > 10000]
print(f'Jumlah berlian dengan harga diatas $10.000: {len(high_prices)}')

Jumlah berlian dengan harga diatas $10.000: 5222


In [14]:
# Filter harga dibawah $1.000
low_prices = prices[prices > 1000]
print(f'Jumlah berlian dengan harga dibawah $1.000: {len(low_prices)}')

Jumlah berlian dengan harga dibawah $1.000: 39416


In [15]:
# Filter harga diantara $1.000-$5.000
prices_1k_to_5k = prices[(prices >= 1000) & (prices <= 5000)]
print(f'Jumlah berlian dengan harga diantara $1.000-$5.000: {len(prices_1k_to_5k)}')

Jumlah berlian dengan harga diantara $1.000-$5.000: 24727


In [16]:
# Filter harga diantara $5.000-$10.000
prices_1k_to_5k = prices[(prices > 5000) & (prices <= 10000)]
print(f'Jumlah berlian dengan harga diantara $5.000-$10.000: {len(prices_1k_to_5k)}')

Jumlah berlian dengan harga diantara $5.000-$10.000: 9492


In [17]:
# Filter carat diatas 1.5
high_carats = carat[carat > 1.5]
print(f'Jumlah berlian dengan carat diatas 1.5: {len(high_carats)}')

Jumlah berlian dengan carat diatas 1.5: 5442


In [18]:
# Filter carat dibawah 1.5
low_carats = carat[carat < 1.5]
print(f'Jumlah berlian dengan carat dibawah 1.5: {len(low_carats)}')

Jumlah berlian dengan carat dibawah 1.5: 47705


### **Filtering Data dengan Pandas**

In [19]:
# Filter berlian dengan kualitas cut 'Ideal'
ideal_diamonds = df[df['cut'] == 'Ideal']
ideal_diamonds.head()

Unnamed: 0  carat    cut color clarity  depth  table  price     x     y  \
0            1   0.23  Ideal     E     SI2   61.5   55.0    326  3.95  3.98   
11          12   0.23  Ideal     J     VS1   62.8   56.0    340  3.93  3.90   
13          14   0.31  Ideal     J     SI2   62.2   54.0    344  4.35  4.37   
16          17   0.30  Ideal     I     SI2   62.0   54.0    348  4.31  4.34   
39          40   0.33  Ideal     I     SI2   61.8   55.0    403  4.49  4.51   

       z  
0   2.43  
11  2.46  
13  2.71  
16  2.68  
39  2.78

In [20]:
# Filter berlian dengan harga diatas $10.000
expensive_diamonds = df[df['price'] > 10000]
expensive_diamonds.head()

Unnamed: 0  carat        cut color clarity  depth  table  price     x  \
21928       21929   1.70      Ideal     J     VS2   60.5   58.0  10002  7.73   
21929       21930   1.03      Ideal     E    VVS2   60.6   59.0  10003  6.50   
21930       21931   1.23  Very Good     G    VVS2   60.6   55.0  10004  6.93   
21931       21932   1.25      Ideal     F     VS2   61.6   55.0  10006  6.93   
21932       21933   2.01  Very Good     I     SI2   61.4   63.0  10009  8.19   

          y     z  
21928  7.74  4.68  
21929  6.53  3.95  
21930  7.02  4.23  
21931  6.96  4.28  
21932  7.96  4.96

## **6. Menghitung Persentil dengan Numpy**


In [21]:
# Menghitung percentile untuk harga
percentile_25 = np.percentile(prices, 25)
percentile_50 = np.percentile(prices, 50)  # median
percentile_75 = np.percentile(prices, 75)

print(f'Percentile 25: ${percentile_25:.2f}')
print(f'Percentile 50 (Median): ${percentile_50:.2f}')
print(f'Percentile 75: ${percentile_75:.2f}')

Percentile 25: $950.00
Percentile 50 (Median): $2401.00
Percentile 75: $5324.25


In [22]:
# Menghitung percentile untuk carat
percentile_25 = np.percentile(carat, 25)
percentile_50 = np.percentile(carat, 50)  # median
percentile_75 = np.percentile(carat, 75)

print(f'Percentile 25: {percentile_25:.2f}')
print(f'Percentile 50 (Median): {percentile_50:.2f}')
print(f'Percentile 75: {percentile_75:.2f}')

Percentile 25: 0.40
Percentile 50 (Median): 0.70
Percentile 75: 1.04


## **7. Membuat Visualisasi Sederhana dengan NumPy dan Pandas**


## **7. Membuat Histogram dengan NumPy**

---




In [23]:
# Membuat histogram untuk harga
hist, bin_edges = np.histogram(prices, bins=10)
print('Frekuensi Histogram')
print(hist)
print('Batas bin Histogram')
print(bin_edges)

Frekuensi Histogram
[25335  9328  7393  3878  2364  1745  1306  1002   863   726]
Batas bin Histogram
[  326.   2175.7  4025.4  5875.1  7724.8  9574.5 11424.2 13273.9 15123.6
 16973.3 18823. ]


## **8. Operasi matematika dengan Numpy**


In [25]:
# Menghitung total harga semua berlian
total_prices = np.sum(prices)
print(f'Tootal harga semua berlian: ${total_prices:.2f}')

Tootal harga semua berlian: $212135217.00


## **9. Menghitung Z-Scores dengan Numpy**

In [26]:
# Menyimpan data numerik ke numpy array
numeric_data = df.select_dtypes(include='number').iloc[:,1:].to_numpy()
# Menyimpan kolom data numerik ke numpy array
col_numeric = df.select_dtypes(include='number').iloc[:,1:].columns.to_list()

# Menghitung mean setiap kolom numerik
mean = np.mean(numeric_data, axis=0)
# Menghitung standar deviasi setap kolom numerik
std = np.std(numeric_data, axis=0)

# Menghitung Z-Scores setiap kolom numerik
zscore_num = (numeric_data - mean) / std

# Ngeprint Z-Value
print(f"5 Value awal dari Z-Value Dari Kolom: \n{col_numeric} : \n{zscore_num[:5,:8]}")

5 Value awal dari Z-Value Dari Kolom: 
['carat', 'depth', 'table', 'price', 'x', 'y', 'z'] : 
[[-1.19816781 -0.17409151 -1.09967199 -0.90409516 -1.58783745 -1.53619556
  -1.57112919]
 [-1.24036129 -1.36073849  1.58552871 -0.90409516 -1.64132529 -1.65877419
  -1.74117497]
 [-1.19816781 -3.38501862  3.37566251 -0.9038445  -1.49869105 -1.45739502
  -1.74117497]
 [-1.07158736  0.45413336  0.24292836 -0.90208985 -1.36497146 -1.31730516
  -1.28771955]
 [-1.02939387  1.08235823  0.24292836 -0.90183918 -1.24016651 -1.21223777
  -1.11767377]]


## **10. Menghitung jumlah Outlier menggunakan Z-Scores dengan Numpy**

In [27]:
# Mencari outlier
outlier = ( zscore_num > 3) | ( zscore_num <-3)

# Menghitung total outlier perkolom
total_z_kolom = np.sum(outlier, axis=0)

# Menghitung berapa outlier untuk seluruh kolom
total_z = np.unique(outlier, return_counts=True)[1][1]


# Menprint total Outlier tiap kolom
print(f"Total Outlier tiap kolom numerik : ")
for index, col in enumerate(col_numeric):
  print(f"{index + 1}. {col} = {total_z_kolom[index]}")
# Menprint total Outlier untuk semua kolom
print(f"\nJumlah Outlier di seluruh kolom adalah : {total_z}")

Total Outlier tiap kolom numerik : 
1. carat = 439
2. depth = 685
3. table = 336
4. price = 1206
5. x = 43
6. y = 34
7. z = 55

Jumlah Outlier di seluruh kolom adalah : 2798


## **11. Membuat Model Linear Regresi Menggunakan Numpy**

In [28]:
# Model Linear Regressi
class LinearRegression:
  def __init__(self, X, y=None, lr=0.01):
    # Params untuk menyimpan parameter dan gradientnya
    self.params = {}

    # inisiasi parameter
    # Menambah col baru dengan semua isinya bernilai 1 ke x
    # yang digunakan agar kita memiliki intercept di rumus linear regresi
    # yang menggunakan vector form
    self.X = np.concatenate((np.ones([np.shape(X)[0], 1]), X),axis=1)
    self.y = y
    # learning rate sebagai konstanta belajar seberapa cepat mengupdate gradient
    self.lr = lr
    # Inisiasi parameter linear regresi dengan menggunakan nilai random
    self.params['W'] = np.random.rand(1, self.X.shape[1])

  def predict(self, X, mode="test"):
    """Untuk Prediksi y Berdasarkan input X menggunakan model linear regresi"""
    if mode == "test":
      # Menambah col baru dengan semua isinya bernilai 1 ke x
      # yang digunakan agar kita memiliki intercept di rumus linear regresi
      # yang menggunakan vector form
      X = np.concatenate((np.ones([np.shape(X)[0], 1]), X),axis=1)
    # Memprediksi y berdasarkan X menggunakan model yang sudah dibuat
    output = np.dot(X, self.params["W"].T)
    return output

  def loss(self, output, y):
    """Menghitung loss"""
    # Menghitung loss menggunakan mean squared error dan dikali 1/2 agar
    # gradientnya nanti gampang dihitung
    return 1/2 * np.mean(np.square(output - y))

  def batch(self, batch_size):
    """Menggunakan mini-batch untuk menghitung loss, output, dan gradien"""
    # Meninisiasi loss dan menshuffle X & y
    loss = 0
    # Menshuffle menggunakan fungsi np.random.permutation() sebagai index
    # lalu menggunakan index tersebut untuk menshuffle X dan y
    indices = np.random.permutation(len(self.y))
    X_shuffle = self.X[indices]
    y_shuffle = self.y[indices]

    # Membagi data menjadi minibatch yg diitung loss nya
    for i in range(0, len(self.y), batch_size):
      end = min(i + batch_size, len(self.y))
      # Membagi data per batch dengan banyak n (training example) sesuai
      # dengan batch_size yang dipilih
      X_batch = X_shuffle[i:end, :]
      y_batch = y_shuffle[i:end]
      # Kalulasi loss per batch
      a = self.calculate(X_batch, y_batch, "train", "gradient_descent")[0]

      # Melakukan running average dari loss sebelumnya agar mendapatkan rata
      # rata loss dari mini batch
      loss = loss + a * (end - i)
    # Return total loss dari loss yang didapatkan menggunakan running average
    # dan dibagi total training (n)
    return loss / len(self.y)


  def calculate(self, X, y, mode="test", solver_type="least_square"):
    """Untuk kalkulasi gradien output dan least square dari model"""
    # Mendapatkan output dari linear regresi
    output = self.predict(X, mode=mode)
    # Bila modenya train
    if mode == "train":
      # Training menggunakan gradient descent
      # Menghitung loss menggunakan output dan y
      loss = self.loss(output, y)

      # Menentukan solver type gradient descent atau metode least square
      if solver_type == "gradient_descent":
        # Menghitung gradient menggunakan rumus dibawah
        self.params['dW'] = np.dot((y[:, np.newaxis] - output).T, X) / len(y)
        # Update parameter berdasarkan gradient dikali konstanta belajar (lr/learning rate)
        self.params['W'] += self.lr * self.params['dW']
      # Bila menggunakan metode least square / metode kuadrat terkecil
      else:
        # Perhitungan menggunakan metode kuadrat terkecil agar mendapatkan
        # Parameter optimal untuk model secara langsung agar meminimalkan
        # loss function
        a = np.linalg.inv(np.dot(X.T, X))
        b = np.dot(X.T, y)
        c = np.dot(a, b)

        # Mengupdate parameter berdasarkan parameter optimal
        self.params['W'] = c[:, np.newaxis].T

    # Return output bila mode test
    else:
      return output

    # Return loss serta output
    return loss, output

  def train(self, solver_type="least_square", epoch=50, batch_size=216):
    """Untuk train model linear regresi"""
    if solver_type == "gradient_descent":
      # Bila solver type gradient descent update parameter dilakukan sampai
      # epoch/iterasi tertentu
      for i in range(epoch):
        # Menghitung loss dari model yang di update parameternya
        loss = self.batch(batch_size)
        print(f"[Epoch {i + 1}] : loss = {loss}")
    else:
      # Menghitung loss yang sudah di update parameternya menggunakan least square/metode kuadrat terkecil
      loss, _ = self.calculate(self.X, self.y, "train", "least_square")
      print(f"loss : {loss}")

Menggunakan Gradient Descent sebagai metode optimasi linear regresi

In [29]:
# Mengambil data untuk feature X dan label y yaitu 'carat' sebagai kolom yang akan di tebak, lalu menormalisasikanya
X = numeric_data[:, 1:] / np.max(numeric_data[:, 1:],axis=0)
y = numeric_data[:, 0]

# Ngesplit data menjadi train dan testing
X_train, y_train, X_test, y_test = X[:40000, :], y[:40000], X[40000:, :], y[40000:]

# Membuat objek linear regresi dengan data tersebut
model = LinearRegression(X_train, y_train, 0.1)

In [30]:
# Melatih model linear regresi dan melihat loss dari model tersebut ke data
# Melatih menggunakan metode gradient descent (Karena datanya terlalu banyak)
model.train("gradient_descent", epoch=50, batch_size=512)

[Epoch 1] : loss = 0.1449712730281827
[Epoch 2] : loss = 0.16745259367676632
[Epoch 3] : loss = 0.19293094791175452
[Epoch 4] : loss = 0.21290611264250492
[Epoch 5] : loss = 0.22684183786394937
[Epoch 6] : loss = 0.23637406007651693
[Epoch 7] : loss = 0.2424100397228051
[Epoch 8] : loss = 0.24641638762273466
[Epoch 9] : loss = 0.24911656932658693
[Epoch 10] : loss = 0.2504776684794837
[Epoch 11] : loss = 0.25189652476482743
[Epoch 12] : loss = 0.252688943100098
[Epoch 13] : loss = 0.2529110021685213
[Epoch 14] : loss = 0.2530116105501276
[Epoch 15] : loss = 0.2532945370283807
[Epoch 16] : loss = 0.25372099267488546
[Epoch 17] : loss = 0.25391697416580444
[Epoch 18] : loss = 0.2542373994045582
[Epoch 19] : loss = 0.254181056935938
[Epoch 20] : loss = 0.25416288301267514
[Epoch 21] : loss = 0.25422355228395893
[Epoch 22] : loss = 0.25422396617988546
[Epoch 23] : loss = 0.2545111072696511
[Epoch 24] : loss = 0.25449068120739565
[Epoch 25] : loss = 0.25457441493993727
[Epoch 26] : loss = 0

In [31]:
# Melakukan Testing
# Mendapatkan prediksi model berdasarkan X_test yaitu test data
output = model.predict(X_test)
print(f"Hasil output atau prediksi y berdasarkan X adalah : \n{output}")
print(f"\nLabel atau y yang asli sebagai perbandingan : \n{y_test}")

# Menghitung seberapa bagus model menggunakan test data menggunakan Mean Squared Error
mse = np.mean(np.square(output - y_test))
print(f"\n\nMean Squared Error dari Testing data Menggunakan Gradient Descent adalah = {mse}")

Hasil output atau prediksi y berdasarkan X adalah : 
[[0.43076683]
 [0.4347615 ]
 [0.43540416]
 ...
 [0.7292124 ]
 [0.82754669]
 [0.75466478]]

Label atau y yang asli sebagai perbandingan : 
[0.41 0.41 0.41 ... 0.7  0.86 0.75]


Mean Squared Error dari Testing data Menggunakan Gradient Descent adalah = 0.04028321277690951


Menggunakan metode kuadrat terkecil sebagai metode optimasi

In [32]:
# Mengambil 15000 data pertama untuk feature X dan 5000 label y yaitu 'carat' sebagai kolom yang akan di tebak
# Data hanya 15000 yang dipakai karena metode kuadrat terkecil tidak dapat dipakai untuk data yang banyak
# Ngesplit data menjadi train dan testing
X_train, y_train, X_test, y_test = X[:15000, :], y[:15000], X[15000:20000, :], y[15000:20000]

# Membuat objek linear regresi dengan data tersebut
model = LinearRegression(X_train, y_train, 0.1)

In [33]:
# Melatih model linear regresi dan melihat loss dari model tersebut ke data
# Melatih menggunakan metode kuadrat terkecil menggunakan 1000 data
model.train("least_square")

loss : 0.21681155676584718


In [34]:
# Melakukan Testing
# Mendapatkan prediksi model berdasarkan X_test yaitu test data
output = model.predict(X_test)
print(f"Hasil output atau prediksi y berdasarkan X adalah : \n{output}")
print(f"\nLabel atau y yang asli sebagai perbandingan : \n{y_test}")

# Menghitung seberapa bagus model menggunakan test data menggunakan Mean Squared Error
mse = np.mean(np.square(output - y_test))
print(f"\n\nMean Squared Error dari Testing data Menggunakan Metode Kuadrat Terkecil adalah = {mse}")

Hasil output atau prediksi y berdasarkan X adalah : 
[[1.22171809]
 [1.01841291]
 [0.99840497]
 ...
 [1.04579726]
 [1.39667305]
 [1.31261814]]

Label atau y yang asli sebagai perbandingan : 
[1.3  1.01 1.   ... 1.05 1.57 1.5 ]


Mean Squared Error dari Testing data Menggunakan Metode Kuadrat Terkecil adalah = 0.20825816177165213


In [1]:
!pip install rise



   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.3/4.3 MB 37.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 49.4 MB/s eta 0:00:00
